#!/bin/bash

POSTGRES_USER=${POSTGRES_USER:-${DB_ENV_POSTGRES_USER}}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-${DB_ENV_POSTGRES_PASSWORD}}

echo "db:*:*:"${POSTGRES_USER}":"${POSTGRES_PASSWORD} > ~/.pgpass
chmod 0600 ~/.pgpass

"$@" -U ${POSTGRES_USER} -h db
